### ISSUE TITLE
Idea for runner

### ISSUE THREAD

**Issue by CRD716** [brentvollebregt/mutli-clipboard#3]
Here's my idea: a batch program that runs multi-clipboard when opened.

What it can do/issues
Runs well with very little code
Very easy to code
I can do it. Yep turns out I can do something.

What I've accomplished:
- [x] Downloading the required things
- [x] Making script
- [x] Making a nice looking runner
- [x] Releasing to GitHub
[Multi-ClipboardRunner.zip](https://github.com/brentvollebregt/multi-clipboard/files/2570008/Multi-ClipboardRunner.zip)

**Comment by CRD716** [comment]
``

**Comment by CRD716** [comment]
``

**Comment by CRD716** [comment]
Don't know what happened, but it closed. It is complete. I just need to figure out how to upload it here

**Comment by brentvollebregt** [comment]
Good job on getting this project working and thank you for your interest.

Unizpping `Multi-ClipboardRunner.zip` contains three files; `Made by 13thWallStudios.txt`, 'Multi-ClipboardRunner - Shortcut' (.ink) and `Multi-ClipboardRunner.bat`.

Discussing these files in order; first `Made by 13thWallStudios.txt`. I don't think this will be required by the project and we know who made it, you, because you have put it here.

For the file 'Multi-ClipboardRunner - Shortcut', I recommend understanding a bit of what shortcuts do; they reference absolute paths to a file/directory. This means just because it works on your computer will not mean it will work on mine as this could be somewhere else on my machine compared to yours. If a user uses the expected way to install this project, then it would be located in their Python distribution. But if someone installs it like expected, then the can simply execute `multi-clipboard` in cmd to open it.

This leads me to the next file `Multi-ClipboardRunner.bat`. If the user has installed the project per what is described in the README.md file, then a simple call of `multi-clipboard` will start the project. This means simply putting the line `multi-clipboard` in a .bat file is sufficient.

I am not saying what you have done here is bad at all, it's good to see people taking interest and trying new things out. You have brought to my attention that the terminal window does stay open which is an issue and something I missed as I have been using and IDE so this window hasn't been popping up for me; thank you for that.

If you want to discuss something I have said then feel free.

**Comment by brentvollebregt** [comment]
Thank you for your input, I have implemented a button that can create shortcuts for users in the form of a VB script.
